export const alertConstants = {
    ALERT_SUCCESS_INFO: 'ALERT_SUCCESS_INFO',
    ALERT_ERROR: 'ALERT_ERROR',
    ALERT_CLEAR: 'ALERT_CLEAR',
    ALERT_BUYING: 'ALERT_BUYING',
    ALERT_DELETING: 'ALERT_DELETING',
    ALERT_CONNECTION_ERROR: 'ALERT_CONNECTION_ERROR'
}

