export const betsConstants = {
    FETCH_BET_PRICE_REQUEST: 'FETCH_BETS_PRICE_REQUEST',
    FETCH_BET_PRICE_SUCCESS: 'FETCH_BETS_PRICE_SUCCESS',
    FETCH_BET_PRICE_FAILURE: 'FETCH_BETS_PRICE_FAILURE',
    DELETE_BET:'DELETE_BET',
    FETCH_BET:'FETCH_BET'
};