export const contractConstants = {
    BUY_CONTRACT_REQUEST: 'BUY_CONTRACT_REQUEST',
    BUY_CONTRACT_SUCCESS: 'BUY_CONTRACT_SUCCESS',
    BUY_CONTRACT_FAILURE: 'BUY_CONTRACT_FAILURE',
    FETCH_CONTRACTS_REQUEST: 'FETCH_CONTRACTS_REQUEST',
    FETCH_CONTRACTS_SUCCESS: 'FETCH_CONTRACTS_SUCCESS',
    FETCH_CONTRACTS_FAILURE: 'FETCH_CONTRACTS_FAILURE',
    FETCH_CONTRACT_REQUEST: 'FETCH_CONTRACT_REQUEST',
    FETCH_CONTRACT_SUCCESS: 'FETCH_CONTRACT_SUCCESS',
    FETCH_CONTRACT_FAILURE: 'FETCH_CONTRACT_FAILURE',
    FETCH_CONTRACT_DETAILS_REQUEST: 'FETCH_CONTRACT_DETAILS_REQUEST',
    FETCH_CONTRACT_DETAILS_SUCCESS:'FETCH_CONTRACT_DETAILS_SUCCESS',
    FETCH_CONTRACT_DETAILS_FAILURE:'FETCH_CONTRACT_DETAILS_FALIURE'
};