export const filterConstants = {
    SELECT_CATEGORY: 'SELECT_CATEGORY',
    UNSELECT_CATEGORY: 'UNSELECT_CATEGORY',
    UPDATE_SEARCH: 'UPDATE_SEARCH',
    UPDATE_SORTED: 'UPDATE_SORTED',
    UPDATE_CURRENT_PAGE: 'UPDATE_CURRENT_PAGE',
    UPDATE_PAGE_SIZE: 'UPDATE_PAGE_SIZE',
    CLEAR_FILTERS: 'CLEAR_FILTERS'
}