export const filterTransactionConstants = {
    UPDATE_TRANSACTION_FILTERS:'UPDATE_TRANSACTION_FILTERS',
    CLEAR_TRANSACTION_FILTERS:'CLEAR_TRANSACTION_FILTERS',
    UPDATE_CURRENT_TRANSACTION_PAGE:'UPDATE_CURRENT_TRANSACTION_PAGE'
}