export const marketsConstants = {
    SET_MARKET_COVER_REQUEST: 'SET_MARKET_COVER_REQUEST',
    SET_MARKET_COVER_SUCCESS: 'SET_MARKET_COVER_SUCCESS',
    SET_MARKET_COVER_FAILURE: 'SET_MARKET_COVER_FAILURE',
    FETCH_MARKETS_REQUEST: 'FETCH_MARKETS_REQUEST',
    FETCH_MARKETS_SUCCESS: 'FETCH_MARKETS_SUCCESS',
    FETCH_MARKETS_FAILURE: 'FETCH_MARKETS_FAILURE',
    CREATE_MARKET_REQUEST: 'CREATE_MARKET_REQUEST',
    CREATE_MARKET_SUCCESS: 'CREATE_MARKET_SUCCESS',
    CREATE_MARKET_FAILURE: 'CREATE_MARKET_FAILURE'
};
