export const marketsConstants = {
    FETCH_MARKETS_REQUEST: 'FETCH_MARKETS_REQUEST',
    FETCH_MARKETS_SUCCESS: 'FETCH_MARKETS_SUCCESS',
    FETCH_MARKETS_FAILURE: 'FETCH_MARKETS_FAILURE',
    CREATE_MARKET_REQUEST: 'CREATE_MARKET_REQUEST',
    CREATE_MARKET_SUCCESS: 'CREATE_MARKET_SUCCESS',
    CREATE_MARKET_FAILURE: 'CREATE_MARKET_FAILURE'
};
