export const offerConstants = {
    FETCH_OFFERS_REQUEST:'FETCH_OFFERS_REQUEST',
    FETCH_OFFERS_SUCCESS:'FETCH_OFFERS_SUCCESS',
    FETCH_OFFERS_FAILURE:'FETCH_OFFERS_FAILURE',
    BUY_SHARES_REQUEST:'BUY_SHARES_REQUEST',
    BUY_SHARES_SUCCESS:'BUY_SHARES_SUCCESS',
    BUY_SHARES_FAILURE:'BUY_SHARES_FAILURE'
}