export const paginationConstants = {
    UPDATE_PAGINATION: 'UPDATE_PAGINATION',
    UPDATE_CONTRACT_PAGINATION:'UPDATE_CONTRACT_PAGINATION',
    UPDATE_OFFERS_PAGINATION:'UPDATE_OFFERS_PAGINATION',
    UPDATE_TRANSACTION_PAGINATION:'UPDATE_TRANSACTION_PAGINATION'
}