export const tokenConstants = {
    SEND_TOKEN_REQUEST: 'SEND_TOKEN_REQUEST',
    SEND_TOKEN_SUCCESS: 'SEND_TOKEN_SUCCESS',
    SEND_TOKEN_FAILURE: 'SEND_TOKEN_FAILURE',
    CHECK_TOKEN_REQUEST: 'CHECK_TOKEN_REQUEST',
    CHECK_TOKEN_SUCCESS: 'CHECK_TOKEN_SUCCESS',
    CHECK_TOKEN_FAILURE: 'CHECK_TOKEN_FAILURE',
    CHANGE_PASSWORD_WITH_TOKEN_REQUEST:'CHANGE_PASSWORD_WITH_TOKEN_REQUEST',
    CHANGE_PASSWORD_WITH_TOKEN_SUCCESS:'CHANGE_PASSWORD_WITH_TOKEN_SUCCESS',
    CHANGE_PASSWORD_WITH_TOKEN_FAILURE:'CHANGE_PASSWORD_WITH_TOKEN_FAILURE'
}