export const transactionConstants = {
    FETCH_TRANSACTIONS_REQUEST:'FETCH_TRANSACTIONS_REQUEST',
    FETCH_TRANSACTIONS_SUCCESS:'FETCH_TRANSACTIONS_SUCCESS',
    FETCH_TRANSACTIONS_FAILURE:'FETCH_TRANSACTIONS_FAILURE',
    FETCH_FILTERED_TRANSACTIONS_REQUEST:'FETCH_FILTERED_TRANSACTIONS_REQUEST',
    FETCH_FILTERED_TRANSACTIONS_SUCCESS:'FETCH_FILTERED_TRANSACTIONS_SUCCESS',
    FETCH_FILTERED_TRANSACTIONS_FAILURE:'FETCH_FILTERED_TRANSACTIONS_FAILURE'
}