export const registerConstants = {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE'
};

export const loginConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT'
}

export const editPasswordConstants = {
    EDIT_PASSWORD_REQUEST: 'EDIT_PASSWORD_REQUEST',
    EDIT_PASSWORD_SUCCESS: 'EDIT_PASSWORD_SUCCESS',
    EDIT_PASSWORD_FAILURE: 'EDIT_PASSWORD_FAILURE',
}